language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t cherlyntong/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cherlyntong/react-test npm test

after_success:
  - docker build -t cherlyntong/multi-client ./client
  - docker build -t cherlyntong/multi-nginx ./nginx
  - docker build -t cherlyntong/multi-server ./server
  - docker build -t cherlyntong/multi-worker ./worker
  # log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push to docker hub
  - docker push cherlyntong/multi-client
  - docker push cherlyntong/multi-nginx
  - docker push cherlyntong/multi-server
  - docker push cherlyntong/multi-worker